name: shophy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.3
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
  
